<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BooksApi.Core\BooksApi.Core.csproj" />
		<ProjectReference Include="..\BooksApi.Persistence\BooksApi.Persistence.csproj" />
	</ItemGroup>
	

</Project>